In [1]:
import torch
import numpy
import matplotlib

In [3]:
inputs = torch.tensor(
    [[.72, .45, .31],
     [.75, .20, .55],
     [.3, .8, .4],
     [.85, .35, .6],
     [.55, .15, .75],
     [.25, .2, .85]]
)

words = ['Dream', 'big', 'and', 'work', 'for', 'it']

In [4]:
d_in = inputs.shape[1]
d_out = 2

In [5]:
torch.manual_seed(123)

w_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
w_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
w_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [6]:
print(w_query)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [7]:
x_2 = inputs[1]

In [8]:
query_2 = x_2 @ w_query
key_2 = x_2 @ w_key
value_2 = x_2 @ w_value
print(query_2)

tensor([0.3131, 1.0017])


In [12]:
# Calculating Q, K, V using X, Wq, Wk, Wv
keys = inputs @ w_key
values = inputs @ w_value
queries = inputs @ w_query

In [13]:
keys.shape

torch.Size([6, 2])

In [14]:
queries

tensor([[0.3494, 0.9504],
        [0.3131, 1.0017],
        [0.3198, 1.0524],
        [0.3842, 1.2000],
        [0.2561, 1.0373],
        [0.1872, 1.0034]])

In [15]:
keys_2 = keys[1]
attn_score_22 = query_2.dot(keys_2)
attn_score_22

tensor(0.6990)

In [16]:
attn_sores_2 = query_2 @ keys.T
attn_sores_2

tensor([0.7021, 0.6990, 0.9867, 0.8707, 0.7880, 0.8624])

In [17]:
attn_scores = queries @ keys.T
attn_scores

tensor([[0.6807, 0.6795, 0.9526, 0.8454, 0.7654, 0.8359],
        [0.7021, 0.6990, 0.9867, 0.8707, 0.7880, 0.8624],
        [0.7350, 0.7315, 1.0337, 0.9113, 0.8248, 0.9029],
        [0.8436, 0.8402, 1.1848, 1.0464, 0.9471, 1.0361],
        [0.7080, 0.7025, 1.0003, 0.8764, 0.7929, 0.8699],
        [0.6680, 0.6606, 0.9486, 0.8254, 0.7465, 0.8210]])

In [18]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_sores_2 / d_k**.5, dim=-1)
attn_weights_2, d_k

(tensor([0.1531, 0.1528, 0.1873, 0.1725, 0.1627, 0.1715]), 2)

In [19]:
tensor = torch.tensor([.1, -.2, .3, -.2, .5])

# Apply the softmax without scaling
softmax_results = torch.softmax(tensor, dim=-1)
print(f"Softmax without scaling: {softmax_results}")

#  Multiply the tensor by 8 and then apply softmax
scaled_tensor = tensor * 8
softmax_scaled_result = torch.softmax(scaled_tensor, dim=-1)
print("Softmax after scaling:", softmax_scaled_result)

Softmax without scaling: tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
Softmax after scaling: tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


In [20]:
import torch.nn as nn

In [40]:
class SelfAttention_v1(nn.Module):
    def __inint__(self, d_in, d_out):
        super().__init__()
        self.w_query = nn.Parameter(torch.rand(d_in, d_out))
        self.w_key = nn.Parameter(torch.rand(d_in, d_out))
        self.w_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        keys = x @ self.w_key
        queries = x @ self.w_query
        values = x @ self.w_value

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**.5, dim=-1
        )

        context_vector = attn_weights @ values
        return context_vector


In [41]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1()

In [43]:
print(sa_v1.state_dict())

OrderedDict()


In [47]:
print(sa_v1.__inint__(3, 2))

None


In [49]:
print(sa_v1.forward(inputs))

tensor([[1.1500, 1.0866],
        [1.1493, 1.0860],
        [1.1515, 1.0878],
        [1.1519, 1.0882],
        [1.1488, 1.0856],
        [1.1479, 1.0850]], grad_fn=<MmBackward0>)
